--<ScriptOptions statementTerminator=";"/>

CREATE TABLE student (
	stid INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(45) NOT NULL,
	SURNAME VARCHAR(45) NOT NULL,
	DEPARTMENT VARCHAR(45) NOT NULL,
	TELEPHONE VARCHAR(45) NOT NULL,
	ADDRESS VARCHAR(45) NOT NULL,
	PRIMARY KEY (ID)
) ENGINE=InnoDB;

